Add value in the documentation file about SonarCloud
pipeline-foundation/Notepads pull request #16
Opened 2021-01-26 18:20 UTC by szlatkow

## Other information

2021-01-27 06:40 UTC, kulov requested changes
What does "Add value in the documentation file" in PR title stand for?
Step 11 - "Select the "Bogus" project" is probably wrong for Notepads project.
Step 21 - Scope for SONAR_GITHUB_TOKEN token must be defined.
Step 23 - rephrase -> Run your workflow manually to analyze the code with SonarCloud for the first time.
Step 24 and step 25 need rephrasing.
Use https:// for pipeline.foundation credits.

2021-01-27 06:45 UTC, kulov commented
Step 23 - specify which workflow needs to be manually run.

2021-01-27 07:24 UTC, ross-bohr reviewed
Please address these

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +1. Go to https://sonarcloud.io/
Create your SonarCloud project

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +10. From the dropdown select "Analyze new project".
Configure SonarCloud project

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +17. Next you have to go to https://github.com/settings/tokens and click " Personal access tokens".
Go to {URL} and...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +19. Then scroll down and select **Generate token**.
Scroll down and select...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +20. Now coppy the token and create another Secret.
Copy...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +21. Set the name token **SONAR_GITHUB_TOKEN** and paste the value from the generated token.
..name **of** the...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +22. No further steps are required for this setup.
this is not needed

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +24. In order to set a "Quality gate" follow the next steps.
Set **Quality Gate**

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +25. After the run go to the Project page.
Go to...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +26. Click on the button "Set new code definition" and select "Previous version".
Click the "Set new code definition" button...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +25. After the run go to the Project page.
NOTE: Make sure first run is completed successfully before proceeding

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +11. Select the "Bogus" project and click "Set Up" button at the top right corner.
Select your project ...

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
>  Built with ❤ by [Pipeline Foundation](http://pipeline.foundation)
must be httpS

2021-01-27 07:24 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +5. Click the button "Choose an organization on Github".
"...." button

2021-01-27 12:11 UTC, ross-bohr reviewed
Please address this additional comments @szlatkow

2021-01-27 12:11 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +1. Go to https://sonarcloud.io/
Please remove all numbering altogether and use bullets instead of numbers. Everywhere

2021-01-27 12:11 UTC, ross-bohr commented on CI-CD_DOCUMENTATION.md
> +#### Create your SonarCloud project.
Please DO NOT end a section title with a dot (Everywhere)

2021-01-27 13:27 UTC, ross-bohr approved these changes

2021-01-27 17:14 UTC, szlatkow commented
@kulov  updated

2021-01-29 15:39 UTC, kulov approved these changes

2021-01-29 15:39 UTC, merged